version: '1.0'
services:
  db_mcontent:
    image: "mongo"
    volumes:
      - db-mcontent:/data/db
      - init-db-mcontent:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=passwordXXX
      - MONGO_INITDB_DATABASE=admin
  mcontent_app:
    build: .
    ports:
      - "3020:3020"
    environment:
      - SERVER_PORT=3020
      - NODE_ENV=dev
      - DB_USER=root
      - DB_PASS=passwordXXX
      - DB_HOST=db_info
      - DB_PORT=27017
      - DB_NAME=admin
      - JWT_CHECK=true
      - JWT_SECRET_KEY=any secret phrase
    volumes:
      - user-avatar-mcontent:/mcontent/files/photo
      - images-slider-mcontent:/mcontent/files/images/slider
      - init-db-mcontent:/mcontent/libs/db.init
volumes:
  db-mcontent:
  user-avatar-mcontent:
  init-db-mcontent:
